### ISSUE TITLE
The original images of Image A and Image B in figure 1

### ISSUE THREAD

**Issue by nieshenx** [SHI-Labs/Smooth-Diffusion#1]
Thanks for your excellent work!
Could you kindly provide the original images of Image A and Image B in Figure 1?  Your results look very impressive, and I would like to verify the accuracy of my reproduction. It would be immensely helpful if you could share the original images, allowing me to make a detailed comparison with the results in your paper.

**Comment by JiayiGuo821** [comment]
Hi, thanks for your interest in smooth diffusion. I have uploaded the images to `images/interpolation`, namely `dog1.png` and `dog2.png`. Remember to use [null-text inversion](https://null-text-inversion.github.io/) and set the text prompt to `a realistic dog` if you want to reproduce the results of stable diffusion shown in the paper. 

We are still working on the code and demo and will release them soon.

**Comment by nieshenx** [comment]
Thanks!
