### ISSUE TITLE
Does this work for video generation?

### ISSUE THREAD

**Issue by Njasa2k** [SHI-Labs/Smooth-Diffusion#10]
Does Smooth-Diffusion work for video generation or something like animatediff?

**Comment by JiayiGuo821** [comment]
Hi @ninjasaid2k, thanks for pointing out the promising direction!

Through image interpolation, some animation-like results can be achieved.

For video generation via smooth diffusion, there are several possible ways:
1) Generate start and end frames and interpolate them.
2) Replace SD with smooth diffusion for existing T2V works that use SD as the base model.

We will keep exploring and updating once there are some new results.
