### ISSUE TITLE
Please provide LoRA in a safetensors format

### ISSUE THREAD

**Issue by bkosowski** [SHI-Labs/Smooth-Diffusion#11]
The crucial asset - LoRA - is in a bin/pickle format. This format is considered unsafe as arbitrary code can be executed this way. This, in turn, prevents Smooth-Diffusion from being adopted more widely.

Please provide the LoRA in a safe `safetensors` format.

**Comment by JiayiGuo821** [comment]
Hi, @bkosowski, thanks for the valuable comment!
We have updated the `assets` and `app.py` to support `.safetensors`.

**Comment by bkosowski** [comment]
Thank you so much, @JiayiGuo821!
