### ISSUE TITLE
Spelling Error in Overview Figure

### ISSUE THREAD

**Issue by mbreuss** [SHI-Labs/Smooth-Diffusion#4]
Hi, thanks for sharing this cool work!
While reading the paper I noticed a minor spelling mistake in one of the Figures, that is also used on the project page and github:

It says "denoisng" instead of "denoising"

![image](https://github.com/SHI-Labs/Smooth-Diffusion/assets/33622678/a4c5fa15-830d-4d62-bd1f-b394702c5744)

**Comment by JiayiGuo821** [comment]
Hi, thanks for pointing out that. The figure is updated on the project page and github, and will be revised in the paper later.

**Comment by mbreuss** [comment]
Closed.
