### ISSUE TITLE
Smooth Diffusion Code release

### ISSUE THREAD

**Issue by olliacc** [SHI-Labs/Smooth-Diffusion#5]
Your project for smooth diffusion looks interesting, do you plan on releasing the code?

**Comment by Ma-Weijian** [comment]
Really fantastic work! Also looking forward to seeing the code!

**Comment by JiayiGuo821** [comment]
Hi all. Thanks for your interest in smooth diffusion. We will release the code and demo within the next week.

**Comment by olliacc** [comment]
any update on the code?

**Comment by JiayiGuo821** [comment]
We are still working on the demo and may release it a little later. We will let you know when everything is done. Thank you for your patience.

**Comment by bwhwang** [comment]
Great work!! Do you change the release plan of code?

**Comment by Njasa2k** [comment]
hoping for release.

**Comment by JiayiGuo821** [comment]
Released. Thanks for your patience!
